// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/oms.proto

package net.parasec.pan.oms.wire;

public final class OMSWire {
  private OMSWire() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OMSRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oms.OMSRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.oms.OMSRequest.Command command = 1;</code>
     */
    int getCommandValue();
    /**
     * <code>.oms.OMSRequest.Command command = 1;</code>
     */
    net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command getCommand();
  }
  /**
   * <pre>
   * the request
   * </pre>
   *
   * Protobuf type {@code oms.OMSRequest}
   */
  public  static final class OMSRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oms.OMSRequest)
      OMSRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OMSRequest.newBuilder() to construct.
    private OMSRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OMSRequest() {
      command_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OMSRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              command_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.parasec.pan.oms.wire.OMSWire.OMSRequest.class, net.parasec.pan.oms.wire.OMSWire.OMSRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code oms.OMSRequest.Command}
     */
    public enum Command
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>BUY = 0;</code>
       */
      BUY(0),
      /**
       * <code>SELL = 1;</code>
       */
      SELL(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>BUY = 0;</code>
       */
      public static final int BUY_VALUE = 0;
      /**
       * <code>SELL = 1;</code>
       */
      public static final int SELL_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Command valueOf(int value) {
        return forNumber(value);
      }

      public static Command forNumber(int value) {
        switch (value) {
          case 0: return BUY;
          case 1: return SELL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Command>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Command> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Command>() {
              public Command findValueByNumber(int number) {
                return Command.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.parasec.pan.oms.wire.OMSWire.OMSRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Command[] VALUES = values();

      public static Command valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Command(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:oms.OMSRequest.Command)
    }

    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>.oms.OMSRequest.Command command = 1;</code>
     */
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.oms.OMSRequest.Command command = 1;</code>
     */
    public net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command getCommand() {
      net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command result = net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command.valueOf(command_);
      return result == null ? net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (command_ != net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command.BUY.getNumber()) {
        output.writeEnum(1, command_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (command_ != net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command.BUY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, command_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.parasec.pan.oms.wire.OMSWire.OMSRequest)) {
        return super.equals(obj);
      }
      net.parasec.pan.oms.wire.OMSWire.OMSRequest other = (net.parasec.pan.oms.wire.OMSWire.OMSRequest) obj;

      boolean result = true;
      result = result && command_ == other.command_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + command_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.parasec.pan.oms.wire.OMSWire.OMSRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * the request
     * </pre>
     *
     * Protobuf type {@code oms.OMSRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oms.OMSRequest)
        net.parasec.pan.oms.wire.OMSWire.OMSRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.parasec.pan.oms.wire.OMSWire.OMSRequest.class, net.parasec.pan.oms.wire.OMSWire.OMSRequest.Builder.class);
      }

      // Construct using net.parasec.pan.oms.wire.OMSWire.OMSRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        command_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSRequest_descriptor;
      }

      public net.parasec.pan.oms.wire.OMSWire.OMSRequest getDefaultInstanceForType() {
        return net.parasec.pan.oms.wire.OMSWire.OMSRequest.getDefaultInstance();
      }

      public net.parasec.pan.oms.wire.OMSWire.OMSRequest build() {
        net.parasec.pan.oms.wire.OMSWire.OMSRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.parasec.pan.oms.wire.OMSWire.OMSRequest buildPartial() {
        net.parasec.pan.oms.wire.OMSWire.OMSRequest result = new net.parasec.pan.oms.wire.OMSWire.OMSRequest(this);
        result.command_ = command_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.parasec.pan.oms.wire.OMSWire.OMSRequest) {
          return mergeFrom((net.parasec.pan.oms.wire.OMSWire.OMSRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.parasec.pan.oms.wire.OMSWire.OMSRequest other) {
        if (other == net.parasec.pan.oms.wire.OMSWire.OMSRequest.getDefaultInstance()) return this;
        if (other.command_ != 0) {
          setCommandValue(other.getCommandValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.parasec.pan.oms.wire.OMSWire.OMSRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.parasec.pan.oms.wire.OMSWire.OMSRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int command_ = 0;
      /**
       * <code>.oms.OMSRequest.Command command = 1;</code>
       */
      public int getCommandValue() {
        return command_;
      }
      /**
       * <code>.oms.OMSRequest.Command command = 1;</code>
       */
      public Builder setCommandValue(int value) {
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.oms.OMSRequest.Command command = 1;</code>
       */
      public net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command getCommand() {
        net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command result = net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command.valueOf(command_);
        return result == null ? net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command.UNRECOGNIZED : result;
      }
      /**
       * <code>.oms.OMSRequest.Command command = 1;</code>
       */
      public Builder setCommand(net.parasec.pan.oms.wire.OMSWire.OMSRequest.Command value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        command_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.oms.OMSRequest.Command command = 1;</code>
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oms.OMSRequest)
    }

    // @@protoc_insertion_point(class_scope:oms.OMSRequest)
    private static final net.parasec.pan.oms.wire.OMSWire.OMSRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.parasec.pan.oms.wire.OMSWire.OMSRequest();
    }

    public static net.parasec.pan.oms.wire.OMSWire.OMSRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OMSRequest>
        PARSER = new com.google.protobuf.AbstractParser<OMSRequest>() {
      public OMSRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OMSRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OMSRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OMSRequest> getParserForType() {
      return PARSER;
    }

    public net.parasec.pan.oms.wire.OMSWire.OMSRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OMSResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:oms.OMSResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.oms.OMSResponse.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.oms.OMSResponse.Status status = 1;</code>
     */
    net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status getStatus();

    /**
     * <code>int32 internal_order_id = 2;</code>
     */
    int getInternalOrderId();
  }
  /**
   * <pre>
   * the response
   * </pre>
   *
   * Protobuf type {@code oms.OMSResponse}
   */
  public  static final class OMSResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:oms.OMSResponse)
      OMSResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OMSResponse.newBuilder() to construct.
    private OMSResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OMSResponse() {
      status_ = 0;
      internalOrderId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OMSResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 16: {

              internalOrderId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.parasec.pan.oms.wire.OMSWire.OMSResponse.class, net.parasec.pan.oms.wire.OMSWire.OMSResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code oms.OMSResponse.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OK = 0;</code>
       */
      OK(0),
      /**
       * <code>NOK = 1;</code>
       */
      NOK(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>OK = 0;</code>
       */
      public static final int OK_VALUE = 0;
      /**
       * <code>NOK = 1;</code>
       */
      public static final int NOK_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      public static Status forNumber(int value) {
        switch (value) {
          case 0: return OK;
          case 1: return NOK;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.parasec.pan.oms.wire.OMSWire.OMSResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:oms.OMSResponse.Status)
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.oms.OMSResponse.Status status = 1;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.oms.OMSResponse.Status status = 1;</code>
     */
    public net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status getStatus() {
      net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status result = net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status.valueOf(status_);
      return result == null ? net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status.UNRECOGNIZED : result;
    }

    public static final int INTERNAL_ORDER_ID_FIELD_NUMBER = 2;
    private int internalOrderId_;
    /**
     * <code>int32 internal_order_id = 2;</code>
     */
    public int getInternalOrderId() {
      return internalOrderId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status.OK.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (internalOrderId_ != 0) {
        output.writeInt32(2, internalOrderId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status.OK.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (internalOrderId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, internalOrderId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.parasec.pan.oms.wire.OMSWire.OMSResponse)) {
        return super.equals(obj);
      }
      net.parasec.pan.oms.wire.OMSWire.OMSResponse other = (net.parasec.pan.oms.wire.OMSWire.OMSResponse) obj;

      boolean result = true;
      result = result && status_ == other.status_;
      result = result && (getInternalOrderId()
          == other.getInternalOrderId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + INTERNAL_ORDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getInternalOrderId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.parasec.pan.oms.wire.OMSWire.OMSResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * the response
     * </pre>
     *
     * Protobuf type {@code oms.OMSResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:oms.OMSResponse)
        net.parasec.pan.oms.wire.OMSWire.OMSResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.parasec.pan.oms.wire.OMSWire.OMSResponse.class, net.parasec.pan.oms.wire.OMSWire.OMSResponse.Builder.class);
      }

      // Construct using net.parasec.pan.oms.wire.OMSWire.OMSResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        status_ = 0;

        internalOrderId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.parasec.pan.oms.wire.OMSWire.internal_static_oms_OMSResponse_descriptor;
      }

      public net.parasec.pan.oms.wire.OMSWire.OMSResponse getDefaultInstanceForType() {
        return net.parasec.pan.oms.wire.OMSWire.OMSResponse.getDefaultInstance();
      }

      public net.parasec.pan.oms.wire.OMSWire.OMSResponse build() {
        net.parasec.pan.oms.wire.OMSWire.OMSResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.parasec.pan.oms.wire.OMSWire.OMSResponse buildPartial() {
        net.parasec.pan.oms.wire.OMSWire.OMSResponse result = new net.parasec.pan.oms.wire.OMSWire.OMSResponse(this);
        result.status_ = status_;
        result.internalOrderId_ = internalOrderId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.parasec.pan.oms.wire.OMSWire.OMSResponse) {
          return mergeFrom((net.parasec.pan.oms.wire.OMSWire.OMSResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.parasec.pan.oms.wire.OMSWire.OMSResponse other) {
        if (other == net.parasec.pan.oms.wire.OMSWire.OMSResponse.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.getInternalOrderId() != 0) {
          setInternalOrderId(other.getInternalOrderId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.parasec.pan.oms.wire.OMSWire.OMSResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.parasec.pan.oms.wire.OMSWire.OMSResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.oms.OMSResponse.Status status = 1;</code>
       */
      public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.oms.OMSResponse.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.oms.OMSResponse.Status status = 1;</code>
       */
      public net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status getStatus() {
        net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status result = net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status.valueOf(status_);
        return result == null ? net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.oms.OMSResponse.Status status = 1;</code>
       */
      public Builder setStatus(net.parasec.pan.oms.wire.OMSWire.OMSResponse.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.oms.OMSResponse.Status status = 1;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int internalOrderId_ ;
      /**
       * <code>int32 internal_order_id = 2;</code>
       */
      public int getInternalOrderId() {
        return internalOrderId_;
      }
      /**
       * <code>int32 internal_order_id = 2;</code>
       */
      public Builder setInternalOrderId(int value) {
        
        internalOrderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 internal_order_id = 2;</code>
       */
      public Builder clearInternalOrderId() {
        
        internalOrderId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:oms.OMSResponse)
    }

    // @@protoc_insertion_point(class_scope:oms.OMSResponse)
    private static final net.parasec.pan.oms.wire.OMSWire.OMSResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.parasec.pan.oms.wire.OMSWire.OMSResponse();
    }

    public static net.parasec.pan.oms.wire.OMSWire.OMSResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OMSResponse>
        PARSER = new com.google.protobuf.AbstractParser<OMSResponse>() {
      public OMSResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new OMSResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OMSResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OMSResponse> getParserForType() {
      return PARSER;
    }

    public net.parasec.pan.oms.wire.OMSWire.OMSResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oms_OMSRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oms_OMSRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_oms_OMSResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_oms_OMSResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030src/main/proto/oms.proto\022\003oms\"T\n\nOMSRe" +
      "quest\022(\n\007command\030\001 \001(\0162\027.oms.OMSRequest." +
      "Command\"\034\n\007Command\022\007\n\003BUY\020\000\022\010\n\004SELL\020\001\"l\n" +
      "\013OMSResponse\022\'\n\006status\030\001 \001(\0162\027.oms.OMSRe" +
      "sponse.Status\022\031\n\021internal_order_id\030\002 \001(\005" +
      "\"\031\n\006Status\022\006\n\002OK\020\000\022\007\n\003NOK\020\001B#\n\030net.paras" +
      "ec.pan.oms.wireB\007OMSWireb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_oms_OMSRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_oms_OMSRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oms_OMSRequest_descriptor,
        new java.lang.String[] { "Command", });
    internal_static_oms_OMSResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_oms_OMSResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_oms_OMSResponse_descriptor,
        new java.lang.String[] { "Status", "InternalOrderId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
